version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.2
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/node-logger"
    versions:
    - 6.2.7
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.2.2
  - dependency-name: "@storybook/client-api"
    versions:
    - 6.1.21
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  commit-message:
    prefix: chore
